In [ ]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector:", null_vector)

Null vector: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 2. Create a vector with values ranging from 10 to 49.
vector_range = np.arange(10, 50)
print("Vector with values ranging from 10 to 49:", vector_range)

Vector with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix_range = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values ranging from 0 to 8:")
print(matrix_range)

3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
nonzero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print("Indices of non-zero elements:", nonzero_indices)

Indices of non-zero elements: (array([0, 1, 4]),)


In [ ]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random array:")
print(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random array:
[[0.60613738 0.64407509 0.9346369  0.85762301 0.43554195 0.4536381
  0.78077537 0.44760582 0.10887687 0.88573482]
 [0.23558304 0.12995502 0.84837414 0.86846656 0.89500408 0.74057578
  0.02014985 0.56068232 0.46658578 0.9058412 ]
 [0.20235857 0.99712752 0.59308126 0.60996054 0.03960511 0.54085622
  0.62503073 0.56961084 0.88084274 0.24145672]
 [0.69115724 0.02630426 0.61051626 0.14352692 0.55897856 0.2144963
  0.28828059 0.73466666 0.47589978 0.58984918]
 [0.56457245 0.55197955 0.79044457 0.00466433 0.04760716 0.54664142
  0.73336784 0.63094641 0.13059796 0.73655785]
 [0.86023137 0.42473006 0.26072456 0.88442146 0.18654915 0.70411521
  0.95301903 0.83032005 0.58626556 0.11831557]
 [0.50018057 0.0770095  0.34971092 0.37635755 0.64173237 0.32738222
  0.27969078 0.62778549 0.8811532  0.67084878]
 [0.88987251 0.58698137 0.99443733 0.82083317 0.03413169 0.54014438
  0.34547916 0.0556538  0.37757249 0.94997854]
 [0.73676205 0.64557685 0.83253982 0.3862412  0.68826606 0.70236786


In [ ]:
# 6. Create a random vector of size 30 and find the mean value.
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Random vector:", random_vector)
print("Mean value:", mean_value)

Random vector: [0.61921476 0.54577828 0.3923337  0.77179173 0.2774989  0.38613557
 0.15312119 0.32581657 0.0768642  0.267807   0.19481521 0.68580486
 0.40320272 0.30880212 0.85135374 0.22189615 0.97734898 0.32295206
 0.68539737 0.51148758 0.20755212 0.57499916 0.61444031 0.76976048
 0.59063543 0.09557573 0.29245644 0.23553302 0.10417571 0.71748484]
Mean value: 0.4394011971308248
